public class Main {
    public static void main(String[] args) {
        System.out.println("Задача 1");
        var dog = 8.0;
        System.out.println("dog="+dog);
        var cat = 3.6;
        System.out.println("cat="+cat);
        var paper = 763789;
        System.out.println("paper="+paper);
        System.out.println("Задача 2");
        dog = dog + 4;
        System.out.println("dog="+dog);
        cat = cat + 4;
        System.out.println("cat="+cat);
        paper = paper + 4;
        System.out.println("paper="+paper);
        System.out.println("Задача 3");
        dog = dog - 3.5;
        System.out.println("dog="+dog);
        cat = cat - 1.6;
        System.out.println("cat="+cat);
        paper = paper - 7639;
        System.out.println("paper="+paper);
        System.out.println("Задача 4");
        var friend = 19;
        System.out.println("friend="+friend);
        friend = friend * 2;
        System.out.println("friend="+friend);
        friend = friend / 7;
        System.out.println("friend="+friend);
        System.out.println("Задача 5");
        var frog = 3.5;
        System.out.println("frog="+frog);
        frog = frog * 10;
        System.out.println("frog="+frog);
        frog = frog / 3.5;
        System.out.println("frog="+frog);
        frog = frog + 4;
        System.out.println("frog="+frog);
        System.out.println("Задача 6");
        var firstBoxer = 78.2;
        var secondBoxer = 82.7;
        var boxersWeing = firstBoxer + secondBoxer;
        System.out.println("Вес двух бойцов "+ boxersWeing + " кг ");
        var differenceWeing = secondBoxer - firstBoxer;
        System.out.println("Разница между весами бойцов "+ differenceWeing + " кг ");
        System.out.println("Задача 7");
        System.out.println("1 способ");
        differenceWeing = secondBoxer - firstBoxer;
        System.out.println("Разница между весами бойцов "+ differenceWeing + " кг ");
        System.out.println("2 способ");
        differenceWeing = secondBoxer % firstBoxer;
        System.out.println("Разница между весами бойцов "+ differenceWeing + " кг ");
        System.out.println("Задача 8");
        var totalTime = 640;
        var oneWoker = 8;
        var totalWorkwers = totalTime / oneWoker;
        System.out.println("Всего работников в компании - "+ totalWorkwers + " человек ");
        totalWorkwers = totalWorkwers + 94;
        totalTime = totalWorkwers * oneWoker;
        System.out.println("Если в компании работает "+ totalWorkwers + " человек, то всего " + totalTime + " часов работы может быть поделено между сотрудниками");
    }
}